datagrid:
    brand:
        options:
            entityHint: brand
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            label:
                label: Label
            logo_url:
                label: Logo Url
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_rest_get
                acl_resource: pim_cnet_enrich_brand_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_rest_delete
                acl_resource: pim_cnet_enrich_brand_delete
                params:
                    - id
                    - customEntityName
        actions:
            edit:
                type:      navigate
                acl_resource: pim_cnet_enrich_brand_edit
                label:     brand.edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                acl_resource: pim_cnet_enrich_brand_delete
                label: brand.delete
                icon:  trash
                link:  delete_link
        filters:
            columns:
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code
                label:
                    type:  search
                    label: Label
                    data_name: rd.label
                logo_url:
                    type: string
                    label: Logo URL
                    data_name: rd.logoUrl

        sorters:
            columns:
                code:
                    data_name: rd.code
                label:
                    data_name: rd.label
                logo_url:
                    data_name: rd.logoUrl
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
