datagrid:
    brand:
        options:
            entityHint: brand
        source:
            type: pim_datasource_default
            entity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: code
            label:
                label: label
            logo_url:
                label: url_logo
        filters:
            columns:
                code:
                    type: string
                    label: Code
                    data_name: rd.code
                label:
                    type: string
                    label: Label
                    data_name: rd.label
        sorters:
            columns:
                code:
                    data_name: rd.code
                label:
                    data_name: rd.label
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
