datagrid:
    brand:
        options:
            entityHint: brand
        source:
            type: pim_datasource_default
            entity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
            repository_method: createDatagridQueryBuilder
        columns:
            logo:
                label: logo
                type: twig
                template: PimCnetConnectorBundle:Property:image.html.twig
                frontend_type: html
                data_name: logo_url
            code:
                label: code
            label:
                label: label
            logo_url:
                label: logo_url
            created:
                label: Created
                type: product_value_datetime
                frontend_type: datetime
            updated:
                label: Updated
                type: product_value_datetime
                frontend_type: datetime
        filters:
            columns:
                code:
                    type: string
                    label: Code
                    data_name: rd.code
                label:
                    type: string
                    label: Label
                    data_name: rd.label
                created:
                    type:             date
                    label:            Created
                    data_name:        rd.created
                    filter_by_having: true
                updated:
                    type:             date
                    label:            Updated
                    data_name:        rd.udapted
                    filter_by_having: true
        sorters:
            columns:
                code:
                    data_name: rd.code
                label:
                    data_name: rd.label
                created:
                    data_name: rd.created
                updated:
                    data_name: rd.udapted
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_edit
                acl_resource: pim_cnet_enrich_brand_edit
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_delete
                acl_resource: pim_cnet_enrich_brand_delete
                params:
                    - id
                    - customEntityName
        actions:
            edit:
                type:      navigate
                label:     brand.edit
                acl_resource: pim_cnet_enrich_brand_edit
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                label: brand.delete
                acl_resource: pim_cnet_enrich_brand_delete
                icon:  trash
                link:  delete_link
