custom_entities:
    brand:
        entity_class: Pim\Bundle\CnetConnectorBundle\Entity\Brand
        actions:
            index:
                service: pim_custom_entity.action.index
            edit:
                form_type: ~
            create:
                form_type: ~
