Acme\Bundle\AppEEBundle\Model\PublishedProductValue:
    type: embeddedDocument
    fields:
        brand:
            embedded: true
            type: entity
            targetEntity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
