Acme\Bundle\AppEEBundle\Model\PublishedProductValue:
    type: embeddedDocument
    fields:
        brand:
            type: entity
            targetEntity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
        textCollection:
            type: raw
