measures_config:
    PrinterMediaType:
        standard: SHEET
        units:
            SHEET:
                symbol: 'sheet'
                convert: [{'mul': 1}]
            ENVELOPE:
                symbol: 'envelope'
                convert: [{'mul': 1}]
            ROLL:
                symbol: 'roll'
                convert: [{'mul': 1}]
            STICKER:
                symbol: 'sticker'
                convert: [{'mul': 1}]
            SLIDE:
                symbol: 'slide'
                convert: [{'mul': 1}]
            PAGE:
                unece_code: 'ZP'
                symbol: 'page'
                convert: [{'mul': 1}]
            CARD:
                unece_code: 'CG'
                symbol: 'card'
                convert: [{'mul': 1}]
            PHOTO:
                symbol: 'photo'
                convert: [{'mul': 1}]
            CASSETTE:
                symbol: 'cassette'
                convert: [{'mul': 1}]
            FILE:
                symbol: 'file'
                convert: [{'mul': 1}]
            TRANSPARENCE:
                symbol: 'transparence'
                convert: [{'mul': 1}]
            DISK:
                unece_code: 'DC'
                symbol: 'disk'
                convert: [{'mul': 1}]
            LABEL:
                symbol: 'label'
                convert: [{'mul': 1}]
            PIECE:
                symbol: 'piece'
                convert: [{'mul': 1}]
