Acme\Bundle\AppBundle\Model\ProductValue:
    type: embeddedDocument
    fields:
        brand:
            embedded: true
            type: entity
            targetEntity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
