Pim\Bundle\CnetConnectorBundle\Entity\Brand:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: pim_cnet_reference_data_brand
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        label:
            type: string
            length: 255
        urlLogo75:
            type: string
            length: 255
        urlLogo200:
            type: string
            length: 255
        urlLogo400:
            type: string
            length: 255
        sortOrder:
            type: integer
    manyToOne:
        manufacturer:
            targetEntity: Pim\Bundle\CnetConnectorBundle\Entity\Manufacturer
            inversedBy: brands
            joinColum:
                name: manufacturer_id
                referencedColumnName: id
    lifecycleCallbacks: { }
