Pim\Bundle\CnetConnectorBundle\Entity\Brand:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: pim_cnet_reference_data_brand
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        label:
            type: string
            length: 255
        logoUrl:
            column: logo_url
            type: string
            length: 255
        sortOrder:
            type: integer
    lifecycleCallbacks: { }
