Pim\Bundle\CnetConnectorBundle\Entity\Manufacturer:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: pim_cnet_reference_data_manufacturer
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        label:
            type: string
            length: 255
        sortOrder:
            type: integer
    oneToMany:
        brands:
            targetEntity: Pim\Bundle\CnetConnectorBundle\Entity\Brand
            mappedBy: manufacturer
    lifecycleCallbacks: { }
